package net.highwayfrogs.editor.games.konami;

import net.highwayfrogs.editor.system.Config;
import net.highwayfrogs.editor.utils.logging.ILogger;

/**
 * Indicates an object is able to load/store its data as a Config.
 * Created by Kneesnap on 11/9/2024.
 */
public interface IConfigData {

    /**
     * Load instance data from a Config object.
     * @param logger the logger to write any messages to
     * @param input  the config to load data from
     */
    void fromConfig(ILogger logger, Config input);

    /**
     * Saves instance data to a Config object.
     */
    default Config toConfig() {
        Config config = new Config("AutoGeneratedNoNameCfg");
        toConfig(config);
        return config;
    }

    /**
     * Saves instance data to a Config object.
     */
    void toConfig(Config output);
}
